In [1]:
import pandas as pd

In [2]:
# # Old way; I also want to get in the unpublishable variants, therefore going to use the other full set of ALEdb varaints
# all_mut_df = pd.read_pickle('../out_assoc_gen_feats.pkl')
# len(all_mut_df)

In [5]:
all_mut_df = pd.read_pickle('../aledb_obs_mut_genes_of_interest_df.pkl')
display(len(all_mut_df), all_mut_df.head())

259

,exp,sample,Position,Mutation Type,Sequence Change,Details,Gene,ALEdb source,genetic,clean genes,bnums,genes of interest
466615,10mM_Lactose_R1,8 47 1 1,4159160,SNP,T→A,L224Q (CTG→CAG),oxyR,private,True,{oxyR},{b3961},{b3961}
303555,10mM_Lactose_R2,9 104 1 2,4158805,SNP,C→A,L106I (CTA→ATA),oxyR,private,True,{oxyR},{b3961},{b3961}
303558,10mM_Lactose_R2,9 46 1 2,4159070,SNP,T→A,L194Q (CTG→CAG),oxyR,private,True,{oxyR},{b3961},{b3961}
366871,10mM_Lactose_R3,10 6 1 3,4159121,SNP,C→A,A211D (GCC→GAC),oxyR,private,True,{oxyR},{b3961},{b3961}
353677,1mM_Gluc_10mM_Lactose_R1,4 49 1 1,4159087,SNP,T→G,L200V (TTG→GTG),oxyR,private,True,{oxyR},{b3961},{b3961}

In [6]:
# oxyR_mut_df = pd.DataFrame()
# for _, m in all_mut_df.iterrows():
#     for f in m['genetic features']:
#         if f['RegulonDB ID'] == 'ECK120000674':
#             oxyR_mut_df = pd.concat([
#                 oxyR_mut_df,
#                 m
#             ], axis=1)
#             break
# oxyR_mut_df = oxyR_mut_df.T
# display(len(oxyR_mut_df), oxyR_mut_df.head())

BNUM_OF_INTEREST = 'b3961'

all_mut_df['gene of interest'] = all_mut_df['genes of interest'].apply(lambda s: True if BNUM_OF_INTEREST in s else False )
oxyR_mut_df = all_mut_df[all_mut_df['gene of interest']].drop(columns=['gene of interest'])
oxyR_mut_df

,exp,sample,Position,Mutation Type,Sequence Change,Details,Gene,ALEdb source,genetic,clean genes,bnums,genes of interest
466615,10mM_Lactose_R1,8 47 1 1,4159160,SNP,T→A,L224Q (CTG→CAG),oxyR,private,True,{oxyR},{b3961},{b3961}
303555,10mM_Lactose_R2,9 104 1 2,4158805,SNP,C→A,L106I (CTA→ATA),oxyR,private,True,{oxyR},{b3961},{b3961}
303558,10mM_Lactose_R2,9 46 1 2,4159070,SNP,T→A,L194Q (CTG→CAG),oxyR,private,True,{oxyR},{b3961},{b3961}
366871,10mM_Lactose_R3,10 6 1 3,4159121,SNP,C→A,A211D (GCC→GAC),oxyR,private,True,{oxyR},{b3961},{b3961}
353677,1mM_Gluc_10mM_Lactose_R1,4 49 1 1,4159087,SNP,T→G,L200V (TTG→GTG),oxyR,private,True,{oxyR},{b3961},{b3961}
...,...,...,...,...,...,...,...,...,...,...,...,...
52948,tpiPAE,17 86 1 1,4159112,SNP,G→A,G236E (GGG→GAG),oxyR,public,True,{oxyR},{b3961},{b3961}
52991,tpiPAE,18 130 1 1,4158984,SNP,G→T,M193I (ATG→ATT),oxyR,public,True,{oxyR},{b3961},{b3961}
53270,tpiPAE,23 79 1 1,4158704,SNP,C→T,T100I (ACA→ATA),oxyR,public,True,{oxyR},{b3961},{b3961}
121563,tpiVCH,25 65 1 1,4159154,SNP,G→T,G212V (GGG→GTG),oxyR,public,True,{oxyR},{b3961},{b3961}
121675,tpiVCH,28 66 1 1,4159190,SNP,T→A,L224Q (CTG→CAG),oxyR,public,True,{oxyR},{b3961},{b3961}

In [7]:
set(oxyR_mut_df.exp)

{'10mM_Lactose_R1',
 '10mM_Lactose_R2',
 '10mM_Lactose_R3',
 '1mM_Gluc_10mM_Lactose_R1',
 '1mM_Gluc_10mM_Lactose_R2',
 '1mM_Gluc_10mM_Lactose_R3',
 '1mM_Gluc_10mM_Lactose_R4',
 '5mM_Gluc_5mM_Lactose_R1',
 '5mM_Gluc_5mM_Lactose_R2',
 '5mM_Gluc_5mM_Lactose_R3',
 '5mM_Gluc_5mM_Lactose_R4',
 'BOP1000-M9-mid-log-37-Glucose4-NH4Cl1-KH2PO43-MgSO40001-O2-pH_at_7_0_LowMg-NC_000913_3gb',
 'BOP1000-M9-mid-log-37-Glucose4-NH4Cl1-KH2PO43-MgSO40001-O2-pH_at_7_0_TAPS-NC_000913_3gb',
 'BOP27_pH_6',
 'C321.∆A',
 'C321.∆A.earlyfix',
 'C321_A_earlyfix',
 'DDB_MS56_strain_verification',
 'GLU_16321-M9-NC_000913_3gb-stationary-37-Glucose2-NH4Cl1-KH2PO43-MgSO4024-O2',
 'GLU_18361-M9-NC_000913_3gb-stationary-37-Glucose2-NH4Cl1-KH2PO43-MgSO4024-O2',
 'GLU_4721-M9-NC_000913_3gb-stationary-37-Glucose2-NH4Cl1-KH2PO43-MgSO4024-O2',
 'HGS',
 'Iron-ALE',
 'MG1655-M9-mid-log-37-Glucose4-NH4Cl1-KH2PO43-MgSO40001-O2-pH_at_9_0_TAPS-NC_000913_3gb',
 'MG1655-delta-mutY_nor_125',
 'MS56',
 'MS56_ALE',
 'MUSE-M9-mid-log-37-Glucose4-NH4Cl1-KH2PO43-MgSO40001-O2-pH_at_5_5_MES-NC_000913_3gb',
 'ROS_eAMP',
 'SDT298',
 'SDT308',
 'SDT309',
 'SDT312',
 'SDT313',
 'SoxR-KO_SUPP',
 'pgiBME',
 'pgiPAE',
 'tpiHSA',
 'tpiPAE',
 'tpiVCH'}

In [8]:
oxyR_mut_df.to_pickle('./targ_mut_df.pkl')