In [1]:
import pandas as pd

In [2]:
var_df = pd.read_csv('iscR_ale_muts.csv')
var_df.fillna('', inplace=True)
var_df

,AA pos,mutation type,mutation effect,mutation source,AA ref seq,AA seq change,mutation count,mutation effect color,selection pressure color,name
0,13,SUB,nonsynonymous substitution,paraquat,A,T,1,#DD8452,#6DCCDA,SUB A13T
1,13,SUB,nonsynonymous substitution,unpublished,A,T,1,#DD8452,#AD8BC9,SUB A13T
2,25,SUB,nonsynonymous substitution,unpublished,P,Q,1,#DD8452,#AD8BC9,SUB P25Q
3,33,SUB,nonsynonymous substitution,unpublished,E,D,1,#DD8452,#AD8BC9,SUB E33D
4,37,SUB,nonsynonymous substitution,paraquat,I,V,1,#DD8452,#6DCCDA,SUB I37V
5,37,SUB,nonsynonymous substitution,unpublished,I,V,1,#DD8452,#AD8BC9,SUB I37V
6,40,INS,truncation,unpublished,,,1,#C44E52,#AD8BC9,INS 40
7,43,SUB,nonsynonymous substitution,unpublished,E,G,10,#DD8452,#AD8BC9,SUB E43G
8,43,SUB,nonsynonymous substitution,unpublished,E,V,1,#DD8452,#AD8BC9,SUB E43V
9,44,SUB,nonsynonymous substitution,unpublished,Q,K,1,#DD8452,#AD8BC9,SUB Q44K
10,53,SUB,nonsynonymous substitution,unpublished,G,V,1,#DD8452,#AD8BC9,SUB G53V
11,55,SUB,nonsynonymous substitution,paraquat,V,L,5,#DD8452,#6DCCDA,SUB V55L
12,55,SUB,nonsynonymous substitution,unpublished,V,L,5,#DD8452,#AD8BC9,SUB V55L
13,87,SUB,nonsynonymous substitution,paraquat,V,A,1,#DD8452,#6DCCDA,SUB V87A
14,87,SUB,nonsynonymous substitution,unpublished,V,A,1,#DD8452,#AD8BC9,SUB V87A
15,90,SUB,nonsynonymous substitution,unpublished,T,P,1,#DD8452,#AD8BC9,SUB T90P
16,92,SUB,nonsynonymous substitution,unpublished,C,Y,1,#DD8452,#AD8BC9,SUB C92Y
17,94,DEL,deletion,unpublished,,,1,#937860,#AD8BC9,DEL 94
18,94,SUB,nonsynonymous substitution,unpublished,G,V,1,#DD8452,#AD8BC9,SUB G94V
19,95,DEL,deletion,unpublished,,,1,#937860,#AD8BC9,DEL 95
20,96,DEL,deletion,unpublished,,,1,#937860,#AD8BC9,DEL 96
21,98,DEL,deletion,unpublished,,,2,#937860,#AD8BC9,DEL 98
22,98,SUB,nonsynonymous substitution,paraquat,C,G,1,#DD8452,#6DCCDA,SUB C98G
23,98,SUB,nonsynonymous substitution,unpublished,C,G,1,#DD8452,#AD8BC9,SUB C98G
24,99,DEL,deletion,unpublished,,,2,#937860,#AD8BC9,DEL 99
25,99,SUB,truncation,unpublished,Q,*,1,#C44E52,#AD8BC9,SUB Q99*
26,100,DEL,deletion,unpublished,,,2,#937860,#AD8BC9,DEL 100
27,101,DEL,deletion,unpublished,,,2,#937860,#AD8BC9,DEL 101
28,101,SUB,nonsynonymous substitution,paraquat,G,D,1,#DD8452,#6DCCDA,SUB G101D
29,101,SUB,nonsynonymous substitution,unpublished,G,D,1,#DD8452,#AD8BC9,SUB G101D
30,104,SUB,nonsynonymous substitution,paraquat,C,S,6,#DD8452,#6DCCDA,SUB C104S
31,104,SUB,nonsynonymous substitution,unpublished,C,S,7,#DD8452,#AD8BC9,SUB C104S
32,106,SUB,nonsynonymous substitution,paraquat,T,P,1,#DD8452,#6DCCDA,SUB T106P
33,106,SUB,nonsynonymous substitution,unpublished,T,P,3,#DD8452,#AD8BC9,SUB T106P
34,106,SUB,nonsynonymous substitution,unpublished,T,S,1,#DD8452,#AD8BC9,SUB T106S
35,107,SUB,nonsynonymous substitution,unpublished,H,L,2,#DD8452,#AD8BC9,SUB H107L
36,113,SUB,nonsynonymous substitution,paraquat,L,F,1,#DD8452,#6DCCDA,SUB L113F
37,113,SUB,nonsynonymous substitution,unpublished,L,F,3,#DD8452,#AD8BC9,SUB L113F
38,114,SUB,nonsynonymous substitution,unpublished,S,I,1,#DD8452,#AD8BC9,SUB S114I
39,133,DEL,truncation,unpublished,,,1,#C44E52,#AD8BC9,DEL 133
40,135,SUB,nonsynonymous substitution,unpublished,V,G,1,#DD8452,#AD8BC9,SUB V135G
41,147,SUB,synonymous substitution,unpublished,A,A,1,#55A868,#AD8BC9,SUB A147A
42,156,SUB,synonymous substitution,unpublished,I,I,1,#55A868,#AD8BC9,SUB I156I

In [3]:
import warnings
warnings.filterwarnings('ignore')


out_df = pd.DataFrame(columns=['AA position', 'mutation count', 'color'])
for g, gdf in var_df.groupby(['AA pos', 'mutation effect color']):
    out_df = out_df.append({
        # display(g, gdf, )
        'AA position': g[0],
        'color': g[1],
        'mutation count': gdf['mutation count'].sum()
    }, ignore_index=True)
out_df

   AA position mutation count    color
0           13              2  #DD8452
1           25              1  #DD8452
2           33              1  #DD8452
3           37              2  #DD8452
4           40              1  #C44E52
5           43             11  #DD8452
6           44              1  #DD8452
7           53              1  #DD8452
8           55             10  #DD8452
9           87              2  #DD8452
10          90              1  #DD8452
11          92              1  #DD8452
12          94              1  #937860
13          94              1  #DD8452
14          95              1  #937860
15          96              1  #937860
16          98              2  #937860
17          98              2  #DD8452
18          99              2  #937860
19          99              1  #C44E52
20         100              2  #937860
21         101              2  #937860
22         101              2  #DD8452
23         104             13  #DD8452
24         106              5  #DD8452
25         107              2  #DD8452
26         113              4  #DD8452
27         114              1  #DD8452
28         133              1  #C44E52
29         135              1  #DD8452
30         147              1  #55A868
31         156              1  #55A868

In [4]:
# the structure for IscR currently being used includes the start Methionine,
# therefore variant residue position is the same as the AA position.
out_df['residue pos'] = out_df['AA position']
out_df.head()

  AA position mutation count    color residue pos
0          13              2  #DD8452          13
1          25              1  #DD8452          25
2          33              1  #DD8452          33
3          37              2  #DD8452          37
4          40              1  #C44E52          40

In [5]:
with open('vars.json', 'w') as outfile:  # for NGL
    outfile.write(out_df.to_json())