In [1]:
import pandas as pd
pd.set_option('display.max_columns', 500)

In [2]:
all_mut_df = pd.read_pickle('../aledb_obs_mut_genes_of_interest_df.pkl')
all_mut_df.head()

,exp,sample,Position,Mutation Type,Sequence Change,Details,Gene,ALEdb source,genetic,clean genes,bnums,genes of interest
466615,10mM_Lactose_R1,8 47 1 1,4159160,SNP,T→A,L224Q (CTG→CAG),oxyR,private,True,{oxyR},{b3961},{b3961}
303555,10mM_Lactose_R2,9 104 1 2,4158805,SNP,C→A,L106I (CTA→ATA),oxyR,private,True,{oxyR},{b3961},{b3961}
303558,10mM_Lactose_R2,9 46 1 2,4159070,SNP,T→A,L194Q (CTG→CAG),oxyR,private,True,{oxyR},{b3961},{b3961}
366871,10mM_Lactose_R3,10 6 1 3,4159121,SNP,C→A,A211D (GCC→GAC),oxyR,private,True,{oxyR},{b3961},{b3961}
353677,1mM_Gluc_10mM_Lactose_R1,4 49 1 1,4159087,SNP,T→G,L200V (TTG→GTG),oxyR,private,True,{oxyR},{b3961},{b3961}

In [3]:
BNUM_OF_INTEREST = 'b2531'

all_mut_df['gene of interest'] = all_mut_df['genes of interest'].apply(lambda s: True if BNUM_OF_INTEREST in s else False )
fur_mut_df = all_mut_df[all_mut_df['gene of interest']].drop(columns=['gene of interest'])
fur_mut_df

,exp,sample,Position,Mutation Type,Sequence Change,Details,Gene,ALEdb source,genetic,clean genes,bnums,genes of interest
424755,BOP_27_pfkA,2 33 1 1,2661691,SNP,C→A,A147A (GCG→GCT),iscR,private,True,{iscR},{b2531},{b2531}
455336,Bop_27_TPP,1 36 1 1,2661664,SNP,G→A,I156I (ATC→ATT),iscR,private,True,{iscR},{b2531},{b2531}
468514,GLU_16321-M9-NC_000913_3gb-stationary-37-Gluco...,11 20 0 1,2661969,SNP,C→G,V55L (GTT→CTT),iscR,private,True,{iscR},{b2531},{b2531}
468596,GLU_16321-M9-NC_000913_3gb-stationary-37-Gluco...,13 25 0 1,2661969,SNP,C→G,V55L (GTT→CTT),iscR,private,True,{iscR},{b2531},{b2531}
468716,GLU_16321-M9-NC_000913_3gb-stationary-37-Gluco...,17 23 0 1,2661969,SNP,C→G,V55L (GTT→CTT),iscR,private,True,{iscR},{b2531},{b2531}
...,...,...,...,...,...,...,...,...,...,...,...,...
231323,emrE_TPP,15 38 1 1,2662014,INS,+T,coding (118/489 nt),iscR,private,True,{iscR},{b2531},{b2531}
123251,pgiKO,19 90 1 1,2662004,SNP,T→A,E43V (GAA→GTA),iscR,public,True,{iscR},{b2531},{b2531}
425021,rpoB_E672K-M9-NC_000913_3gb-stationary-37-Gluc...,8 46 0 1,2661857,SNP,C→T,C92Y (TGT→TAT),iscR,private,True,{iscR},{b2531},{b2531}
424924,rpoB_E672K-M9-NC_000913_3gb-stationary-37-Gluc...,10 12 1 1,2661831,DEL,Δ9 bp,coding (293‐301/489 nt),iscR,private,True,{iscR},{b2531},{b2531}
424977,rpoB_E672K-M9-NC_000913_3gb-stationary-37-Gluc...,12 4 0 1,2661831,DEL,Δ9 bp,coding (293‐301/489 nt),iscR,private,True,{iscR},{b2531},{b2531}

In [4]:
fur_mut_df.to_pickle('./targ_mut_df.pkl')